version: "3.5"
services:
  web:
    image: python:3.11-alpine
    container_name: flask_app
    build:
      context: .
    command: >
      sh -c "flask db init &&
      flask db migrate -m "init" &&
      flask db upgrade &&
      flask run -h 0.0.0.0 -p 5005"
    volumes:
      - .:/app
    ports:
      - "5005:5005"
    env_file:
      - .env
